### ISSUE TITLE
:bug: CSRF Token unobtainable since syncthing commit 089fca23

### ISSUE THREAD

**Issue by protodj** [syncthing/syncthing-cli#13]
syncthing-cli fails with "Failed to get CSRF token" since the token was renamed from 
```
CSRF-Token=
```
to
```
CSRF-Token-[ID]=
```
Due to syncthing's auto-update this change is already released and renders the cli unuseable.

**Comment by protodj** [comment]
something is not right, it now crashes (see log)
could it be when the following is executed
```go
client.id = request.Header.Get("X-Syncthing-ID")
```
the request is not done and thus returns null?
```
$> syncthing-cli id
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.getClient(0xc2080560c0, 0xc20801e820)
	/go/src/github.com/syncthing/syncthing-cli/client.go:53 +0x89b
main.httpGet(0xc2080560c0, 0x832830, 0x14, 0x0)
	/go/src/github.com/syncthing/syncthing-cli/client.go:99 +0x33
main.generalStatus(0xc2080560c0)
	/go/src/github.com/syncthing/syncthing-cli/cmd_general.go:62 +0x46
github.com/AudriusButkevicius/cli.Command.Run(0x7f4690, 0x6, 0x0, 0x0, 0x880df0, 0x55, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/AudriusButkevicius/cli/command.go:108 +0xe98
github.com/AudriusButkevicius/cli.(*App).Run(0xc20801e680, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/AudriusButkevicius/cli/app.go:131 +0xbcd
github.com/AudriusButkevicius/cli.(*App).RunAndExitOnError(0xc20801e680)
	/go/src/github.com/AudriusButkevicius/cli/app.go:142 +0x57
main.main()
	/go/src/github.com/syncthing/syncthing-cli/main.go:60 +0x5bf

goroutine 6 [select]:
net/http.(*persistConn).readLoop(0xc20802e210)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 7 [select]:
net/http.(*persistConn).writeLoop(0xc20802e210)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
```
